### ISSUE TITLE
RUST_BACKTRACE=1 should be set

### ISSUE THREAD

**Issue by omo** [rust-lang/rust-playpen#119]
The error message of rustc internal compiler errors asks this.

It'd be great if we can post a reproduction code on play.rust-lang.org and
the compiler developer sees the live diagnose information there.

**Comment by zazdxscf** [comment]
Depends on: https://github.com/rust-lang/rust/issues/29293

**Comment by jonas-schievink** [comment]
> Depends on: rust-lang/rust#29293

That only happens when rustc is compiled with debuginfo btw, so it shouldn't affect playpen

**Comment by respeccing** [comment]
> That only happens when rustc is compiled with debuginfo btw, so it shouldn't affect playpen

You're right - I misunderstood what `Mode: Debug` means in playpen: "debug assertions on"(--enable-debug-assertions) is not the same as debugging info on(--enable-debuginfo).

**Comment by respeccing** [comment]
Looks like an env var could only be set in `playpen.c`: https://github.com/thestinger/playpen/blob/f8becccff56827c1d9ed70f0edc9470bf408bb86/playpen.c#L774-L780

Perhaps if `rustc` had an arg that would do the same thing as the `RUST_BACKTRACE` env var, that would be preferable ? (and while at it it would be even better if this arg could override the env var - I found myself in need of forcing that which is why I made a [variant](https://github.com/respeccing/gentooskyline/blob/50706024aceee84d27a2b829a40048dfdc336a1e/system/Z575/OSes/gentoo/on_baremetal/filesystem_now/gentoo/home/zazdxscf/build/1nonpkgs/rust/equivalent_of_unset_RUST_BACKTRACE.patch) as `RUST_BACKTRACE=disabled` to mean the same as the env var being unset.)

**Comment by respeccing** [comment]
Can probably close this one now.
