### ISSUE TITLE
is.gd link shortener is immediately killed by reddit's spam filter

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust-playpen#25]
Any comment or post containing an is.gd link gets deleted as spam and requires manual moderator attention to override. Us moderators of /r/rust are looking out for and approving comments with playpen links, and the subreddit is low-enough traffic that this is perfectly workable for now; however other subreddits and other sites with spam filters will not be so vigilant about it.

Long term, it would nice if the playpen didn't use something that easily pings spam filters to make sharing code more natural.

**Comment by sinistersnare** [comment]
I think this can be fixed by using Automoderator (like my previous comment). Now that automod is included in reddit by default it will be much easier to implement. I will test the [un-spam list](http://www.reddit.com/r/AutoModerator/wiki/common_conditions) on my personal sub reddit then message the mods. I will report back if this issue should be closed.

Thanks!

**Comment by huonw** [comment]
We already use auto moderator for this purpose on /r/rust but it doesn't solve the issue on any other subreddits or HN etc.

**Comment by sinistersnare** [comment]
Yup, well, Im not sure how well this could be fixed, or if it is possible at all, without having non-is.gd shortened links.

**Comment by huonw** [comment]
Closed by #102, thanks @whipsch!
